### ISSUE TITLE
Publish a gem

### ISSUE THREAD

**Issue by esigler** [PagerDuty/lita-enhance#6]
lita-enhance is awesome!  To get it listed in the [lita plugins directory](https://www.lita.io/plugins), a gem will need to be published.

It should be as simple as:
```
rake release
```

The PagerDuty rubygems.org account creds are in the shared password system.

**Comment by ranjib** [comment]
whats stopping us from doing so ? :-) :+1: Do we need more code review ? specs anything like that?

**Comment by dougbarth** [comment]
https://rubygems.org/gems/lita-enhance published.
